// Gatsby/GatsbySearch/src/pages/search.tsx
import React, { useState, useEffect } from 'react';
import { mockDoctors } from '../data/mockDoctors';
import type { Doctor } from '../types';

const SearchPage: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [specialty, setSpecialty] = useState('');
  const [location, setLocation] = useState('');

  // Get specialty from URL query parameter
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      const specialtyParam = params.get('specialty');
      if (specialtyParam) {
        setSpecialty(specialtyParam);
      }
    }
  }, []);

  const filteredDoctors = mockDoctors.filter((doctor: Doctor) => {
    const matchesSearch =
      searchTerm === '' ||
      doctor.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      doctor.specialty.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesSpecialty = !specialty || doctor.specialty === specialty;
    const matchesLocation =
      !location ||
      doctor.location.toLowerCase().includes(location.toLowerCase());
    return matchesSearch && matchesSpecialty && matchesLocation;
  });

  const specialties = Array.from(new Set(mockDoctors.map((d) => d.specialty)));
  const locations = Array.from(new Set(mockDoctors.map((d) => d.location)));

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Navigation */}
      <nav className="bg-white shadow-md">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between h-16">
            <a href="http://localhost:9000" className="flex items-center gap-2">
              <svg
                className="w-8 h-8 text-primary-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"
                />
              </svg>
              <span className="text-xl font-bold text-gray-900">
                DoctorBook
              </span>
            </a>

            <div className="flex items-center gap-6">
              <a
                href="http://localhost:9000"
                className="text-gray-700 hover:text-primary-600 font-medium transition-colors"
              >
                Home
              </a>
              <a
                href="/search"
                className="text-primary-600 font-medium"
              >
                Search
              </a>
            </div>
          </div>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">
            Find a Doctor
          </h1>
          <p className="text-gray-600">
            Search from our directory of verified healthcare professionals
          </p>
        </div>

        {/* Search Filters */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search by name..."
              className="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
            />
            <select
              value={specialty}
              onChange={(e) => setSpecialty(e.target.value)}
              className="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
            >
              <option value="">All Specialties</option>
              {specialties.map((spec) => (
                <option key={spec} value={spec}>
                  {spec}
                </option>
              ))}
            </select>
            <select
              value={location}
              onChange={(e) => setLocation(e.target.value)}
              className="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
            >
              <option value="">All Locations</option>
              {locations.map((loc) => (
                <option key={loc} value={loc}>
                  {loc}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* Results */}
        <div>
          <p className="text-gray-600 mb-4">
            Found {filteredDoctors.length} doctor{filteredDoctors.length !== 1 ? 's' : ''}
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredDoctors.map((doctor: Doctor) => (
              <a
                key={doctor.id}
                href={`http://localhost:9002/doctor/${doctor.id}`}
                className="bg-white rounded-lg shadow-md hover:shadow-xl transition-shadow p-6"
              >
                <div className="flex flex-col items-center text-center">
                  <img
                    src={doctor.image}
                    alt={doctor.name}
                    className="w-32 h-32 rounded-full object-cover mb-4"
                  />
                  <h3 className="text-xl font-bold text-gray-900 mb-1">
                    {doctor.name}
                  </h3>
                  <p className="text-primary-600 font-medium mb-2">
                    {doctor.specialty}
                  </p>
                  <div className="flex items-center gap-1 mb-2">
                    <span className="text-yellow-400">★</span>
                    <span className="text-sm font-medium text-gray-700">
                      {doctor.rating}
                    </span>
                    <span className="text-sm text-gray-500">
                      ({doctor.reviews} reviews)
                    </span>
                  </div>
                  <div className="flex items-center gap-2 text-sm text-gray-600">
                    <svg
                      className="w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
                      />
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
                      />
                    </svg>
                    {doctor.location}
                  </div>
                  <button className="mt-4 w-full px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 transition-colors">
                    View Profile
                  </button>
                </div>
              </a>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default SearchPage;

export const Head = () => (
  <>
    <title>Search Doctors | DoctorBook</title>
    <meta name="description" content="Search for doctors by specialty, location, and more" />
  </>
);

// SvelteKit/SvelteKitSearch/src/routes/search/+page.svelte
<script lang="ts">
	import SearchWidget from '$lib/components/SearchWidget.svelte';
	import type { PageData } from './$types';

	export let data: PageData;
</script>

<svelte:head>
	<title>Search Doctors - MojLekarz</title>
	<meta name="description" content="Find the best doctors for your needs" />
</svelte:head>

<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
	<h1 class="text-3xl font-bold text-gray-900 mb-8">Search Doctors</h1>

	<!-- Search Bar -->
	<div class="mb-8">
		<SearchWidget />
	</div>

	<!-- Search Results Summary -->
	<div class="mb-6">
		<p class="text-gray-600">
			Found <span class="font-semibold">{data.doctors.length}</span> doctor(s)
			{#if data.filters.query}
				<span>
					matching "<span class="font-semibold">{data.filters.query}</span>"
				</span>
			{/if}
			{#if data.filters.specialty !== 'all'}
				<span>
					in <span class="font-semibold">{data.filters.specialty}</span>
				</span>
			{/if}
			{#if data.filters.location !== 'all'}
				<span>
					near <span class="font-semibold">{data.filters.location}</span>
				</span>
			{/if}
		</p>
	</div>

	<!-- Results -->
	<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
		{#each data.doctors as doctor}
			<a
				href="http://localhost:5002/doctor/{doctor.id}"
				class="bg-white rounded-lg shadow-md hover:shadow-lg transition-shadow p-6"
			>
				<div class="flex items-start mb-4">
					<div class="flex-shrink-0">
						<div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center">
							<span class="text-2xl font-bold text-blue-600">
								{doctor.name.split(' ')[1]?.charAt(0) || 'D'}
							</span>
						</div>
					</div>
					<div class="ml-4 flex-1">
						<h3 class="text-lg font-semibold text-gray-900">{doctor.name}</h3>
						<p class="text-blue-600">{doctor.specialty}</p>
					</div>
				</div>

				<div class="space-y-2 text-sm text-gray-600">
					<div class="flex items-center">
						<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
							/>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
							/>
						</svg>
						{doctor.location}
					</div>

					<div class="flex items-center">
						<svg class="w-4 h-4 mr-2 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
							<path
								d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
							/>
						</svg>
						{doctor.rating} ({doctor.reviewCount} reviews)
					</div>

					<div class="flex items-center">
						<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
							/>
						</svg>
						{doctor.experience} years experience
					</div>
				</div>

				<div class="mt-4 pt-4 border-t border-gray-200">
					<p class="text-sm text-gray-600 line-clamp-2">{doctor.bio}</p>
				</div>
			</a>
		{/each}
	</div>

	{#if data.doctors.length === 0}
		<div class="text-center py-12">
			<p class="text-gray-500 text-lg">No doctors found matching your criteria.</p>
			<p class="text-gray-400 mt-2">Try adjusting your search filters.</p>
		</div>
	{/if}
</div>
