// ModernJS/HostApp/src/routes/page.tsx
import { lazy, Suspense } from 'react';

// Dynamically import the SearchWidget from the Search MFE using Module Federation
const SearchWidget = lazy(() => import('search_mfe/SearchWidget'));

export default function HomePage() {
  return (
    <div>
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-primary-600 to-primary-800 text-white py-20">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-5xl font-bold mb-6">Find Your Perfect Doctor</h1>
          <p className="text-xl mb-8 text-primary-100">Book appointments with verified healthcare professionals across Poland</p>
        </div>
      </section>

      {/* Search Widget Section */}
      <section className="container mx-auto px-4 -mt-10 relative z-10">
        <Suspense fallback={
          <div className="bg-white rounded-lg shadow-xl p-6 max-w-2xl mx-auto">
            <div className="animate-pulse">
              <div className="h-8 bg-gray-200 rounded w-1/3 mb-4"></div>
              <div className="h-12 bg-gray-200 rounded mb-4"></div>
              <div className="h-12 bg-gray-200 rounded"></div>
            </div>
          </div>
        }>
          <SearchWidget />
        </Suspense>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-16">
        <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">Why Choose nowoczesnylekarz?</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <div className="bg-primary-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-2">Verified Doctors</h3>
            <p className="text-gray-600">All doctors are verified and certified healthcare professionals</p>
          </div>

          <div className="text-center">
            <div className="bg-primary-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-2">Quick Booking</h3>
            <p className="text-gray-600">Book appointments instantly with real-time availability</p>
          </div>

          <div className="text-center">
            <div className="bg-primary-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
              </svg>
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-2">Trusted Reviews</h3>
            <p className="text-gray-600">Read genuine reviews from verified patients</p>
          </div>
        </div>
      </section>

      {/* Specialties Section */}
      <section className="bg-white py-16">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-12">Popular Specialties</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { name: 'Cardiology', icon: '❤️' },
              { name: 'Dermatology', icon: '👨‍⚕️' },
              { name: 'Pediatrics', icon: '👶' },
              { name: 'Orthopedics', icon: '🦴' },
              { name: 'Neurology', icon: '🧠' },
              { name: 'Ophthalmology', icon: '👁️' },
              { name: 'Psychiatry', icon: '💭' },
              { name: 'Gastroenterology', icon: '🏥' },
            ].map((specialty) => (
              <a
                key={specialty.name}
                href={`/search?specialty=${specialty.name}`}
                className="p-6 bg-gray-50 rounded-lg text-center hover:bg-primary-50 hover:shadow-md transition-all"
              >
                <div className="text-4xl mb-2">{specialty.icon}</div>
                <div className="font-medium text-gray-900">{specialty.name}</div>
              </a>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-primary-600 text-white py-16">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Find Your Doctor?</h2>
          <p className="text-xl mb-8 text-primary-100">Join thousands of patients who trust nowoczesnylekarz</p>
          <a
            href="/search"
            className="inline-block px-8 py-4 bg-white text-primary-600 font-bold rounded-lg hover:bg-gray-100 transition-colors"
          >
            Search Now
          </a>
        </div>
      </section>
    </div>
  );
}

// SvelteKit/SvelteKitHost/src/routes/+page.svelte
<script lang="ts">
	import RemoteSearchWidget from '$lib/components/RemoteSearchWidget.svelte';
</script>

<svelte:head>
	<title>MojLekarz - Find Your Doctor</title>
	<meta name="description" content="Search and find the best doctors near you" />
</svelte:head>

<div class="min-h-screen">
	<!-- Hero Section -->
	<div class="bg-gradient-to-r from-blue-500 to-blue-700 text-white py-20">
		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
			<div class="text-center">
				<h1 class="text-4xl md:text-5xl font-bold mb-6">
					Find and Book the Best Doctors
				</h1>
				<p class="text-xl mb-8">
					Search from thousands of verified healthcare professionals
				</p>
				
				<!-- Search Bar Component - Loaded via Module Federation -->
				<div class="max-w-3xl mx-auto text-left text-gray-900">
					<RemoteSearchWidget />
				</div>
			</div>
		</div>
	</div>

	<!-- Features Section -->
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<div class="grid grid-cols-1 md:grid-cols-3 gap-8">
			<div class="text-center">
				<div class="bg-blue-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
					<svg class="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
					</svg>
				</div>
				<h3 class="text-xl font-semibold mb-2">Easy Search</h3>
				<p class="text-gray-600">Find doctors by specialty, location, or name</p>
			</div>

			<div class="text-center">
				<div class="bg-blue-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
					<svg class="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
					</svg>
				</div>
				<h3 class="text-xl font-semibold mb-2">Verified Doctors</h3>
				<p class="text-gray-600">All doctors are verified healthcare professionals</p>
			</div>

			<div class="text-center">
				<div class="bg-blue-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
					<svg class="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
					</svg>
				</div>
				<h3 class="text-xl font-semibold mb-2">Online Booking</h3>
				<p class="text-gray-600">Book appointments instantly online</p>
			</div>
		</div>
	</div>

	<!-- Popular Specialties -->
	<div class="bg-gray-100 py-16">
		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
			<h2 class="text-3xl font-bold text-center mb-12">Popular Specialties</h2>
			<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
				{#each ['Cardiologist', 'Dermatologist', 'Pediatrician', 'Dentist', 'Orthopedist', 'Psychiatrist', 'Gynecologist', 'Neurologist'] as specialty}
					<a
						href="http://localhost:5001/search?specialty={specialty.toLowerCase()}"
						class="bg-white rounded-lg p-6 text-center hover:shadow-md transition-shadow cursor-pointer"
					>
						<p class="font-medium text-gray-800">{specialty}</p>
					</a>
				{/each}
			</div>
		</div>
	</div>

	<!-- Microfrontend Info Section -->
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<div class="bg-blue-50 rounded-lg p-8">
			<h2 class="text-2xl font-bold text-gray-900 mb-4">SvelteKit Microfrontends</h2>
			<p class="text-gray-700 mb-4">
				This application demonstrates a microfrontend architecture using SvelteKit and Module Federation.
			</p>
			<div class="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
				<div class="bg-white rounded p-4">
					<h3 class="font-semibold text-blue-600 mb-2">Host App (Port 5000)</h3>
					<p class="text-sm text-gray-600">Main shell application that consumes remote components</p>
				</div>
				<div class="bg-white rounded p-4">
					<h3 class="font-semibold text-blue-600 mb-2">Search MFE (Port 5001)</h3>
					<p class="text-sm text-gray-600">Exposes SearchWidget via Module Federation</p>
				</div>
				<div class="bg-white rounded p-4">
					<h3 class="font-semibold text-blue-600 mb-2">Doctor MFE (Port 5002)</h3>
					<p class="text-sm text-gray-600">SSR-enabled doctor profile pages</p>
				</div>
			</div>
		</div>
	</div>

	<!-- Call to Action -->
	<div class="bg-blue-600 text-white py-12">
		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
			<h2 class="text-3xl font-bold mb-4">Ready to Find Your Doctor?</h2>
			<p class="text-xl mb-8">Start your search now and book an appointment today</p>
			<a
				href="http://localhost:5001/search"
				class="bg-white text-blue-600 px-8 py-3 rounded-lg hover:bg-gray-100 transition-colors font-semibold inline-block"
			>
				Search All Doctors
			</a>
		</div>
	</div>
</div>
